 
SELECT 
G AS GAME_NUM,
DATE AS GAME_DATE,
START_ET AS TIME,
COLUMN6 AS HOME_AWAY,
OPPONENT,
STREAK AS WIN_STREAK,
NOTES AS NBA_CUP
INTO CLEAN_SCHEDULE
FROM raw_schedule;
SELECT * FROM CLEAN_SCHEDULE;
