-- DELETE AWAY GAMES--

SELECT * FROM CLEAN_SCHEDULE;

DELETE FROM CLEAN_SCHEDULE
WHERE HOME_AWAY LIKE '%@%' ; 

ALTER TABLE CLEAN_SCHEDULE
DROP COLUMN HOME_AWAY;

SELECT * FROM CLEAN_SCHEDULE; 



