--SPLIT GAME_DATE--
SELECT *,
	YEAR (GAME_DATE) AS YEAR,
	MONTH (GAME_DATE) AS MONTH, 
	DATENAME (WEEKDAY, GAME_DATE) AS DAY_OF_WEEK
INTO CELTICS_SCHEDULE
FROM CLEAN_SCHEDULE;

ALTER TABLE CELTICS_SCHEDULE
DROP COLUMN GAME_DATE

SELECT * FROM CELTICS_SCHEDULE;